/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2021-05-11 08:22:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class productContent_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!--[if lt IE 7]>      <html class=\"no-js lt-ie9 lt-ie8 lt-ie7\"> <![endif]-->\r\n");
      out.write("<!--[if IE 7]>         <html class=\"no-js lt-ie9 lt-ie8\"> <![endif]-->\r\n");
      out.write("<!--[if IE 8]>         <html class=\"no-js lt-ie9\"> <![endif]-->\r\n");
      out.write("<!--[if gt IE 8]><!--> <html class=\"no-js\"> <!--<![endif]-->\r\n");
      out.write("\t<head>\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\t<title>BIT KURLY</title>\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t<meta name=\"description\" content=\"Free HTML5 Template by FREEHTML5.CO\" />\r\n");
      out.write("\t<meta name=\"keywords\" content=\"free html5, free template, free bootstrap, html5, css3, mobile first, responsive\" />\r\n");
      out.write("\t<meta name=\"author\" content=\"FREEHTML5.CO\" />\r\n");
      out.write("<style>\r\n");
      out.write("    *{\r\n");
      out.write("        font-family: sans-serif;\r\n");
      out.write("    }  \r\n");
      out.write("    .com-sm-3{\r\n");
      out.write("        width: 500px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("   .btn_delete, .btn_update, .btn_list {\r\n");
      out.write("    width:80px;\r\n");
      out.write("    height:45px;\r\n");
      out.write("    color:#fff;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    border:none;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("    \r\n");
      out.write("</style>\r\n");
      out.write("  <!-- \r\n");
      out.write("\t//////////////////////////////////////////////////////\r\n");
      out.write("\r\n");
      out.write("\tFREE HTML5 TEMPLATE \r\n");
      out.write("\tDESIGNED & DEVELOPED by FREEHTML5.CO\r\n");
      out.write("\t\t\r\n");
      out.write("\tWebsite: \t\thttp://freehtml5.co/\r\n");
      out.write("\tEmail: \t\t\tinfo@freehtml5.co\r\n");
      out.write("\tTwitter: \t\thttp://twitter.com/fh5co\r\n");
      out.write("\tFacebook: \t\thttps://www.facebook.com/fh5co\r\n");
      out.write("\r\n");
      out.write("\t//////////////////////////////////////////////////////\r\n");
      out.write("\t -->\r\n");
      out.write("\r\n");
      out.write("  \t<!-- Facebook and Twitter integration -->\r\n");
      out.write("\t<meta property=\"og:title\" content=\"\"/>\r\n");
      out.write("\t<meta property=\"og:image\" content=\"\"/>\r\n");
      out.write("\t<meta property=\"og:url\" content=\"\"/>\r\n");
      out.write("\t<meta property=\"og:site_name\" content=\"\"/>\r\n");
      out.write("\t<meta property=\"og:description\" content=\"\"/>\r\n");
      out.write("\t<meta name=\"twitter:title\" content=\"\" />\r\n");
      out.write("\t<meta name=\"twitter:image\" content=\"\" />\r\n");
      out.write("\t<meta name=\"twitter:url\" content=\"\" />\r\n");
      out.write("\t<meta name=\"twitter:card\" content=\"\" />\r\n");
      out.write("\r\n");
      out.write("\t<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->\r\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet' type='text/css'> -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Animate.css -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../assets/css/animate.css\">\r\n");
      out.write("\t<!-- Icomoon Icon Fonts-->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../assets/css/icomoon.css\">\r\n");
      out.write("\t<!-- Bootstrap  -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../assets/css/bootstrap.css\">\r\n");
      out.write("\t<!-- Owl Carousel -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../assets/css/owl.carousel.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../assets/css/owl.theme.default.min.css\">\r\n");
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../assets/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Modernizr JS -->\r\n");
      out.write("\t<script src=\"js/modernizr-2.6.2.min.js\"></script>\r\n");
      out.write("\t<!-- FOR IE9 below -->\r\n");
      out.write("\t<!--[if lt IE 9]>\r\n");
      out.write("\t<script src=\"js/respond.min.js\"></script>\r\n");
      out.write("\t<![endif]-->\r\n");
      out.write("\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t<header style=\"padding-bottom: 3px\">\r\n");
      out.write("\t\t<div class=\"container text-center\">\r\n");
      out.write("\t\t\t<div class=\"fh5co-navbar-brand\">\r\n");
      out.write("\t\t\t\t <a class=\"fh5co-logo\" href=\"../index.jsp\"><img src=\"../assets/images/logo.png\" style=\"height: 110px\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<nav id=\"fh5co-main-nav\" role=\"navigation\" style=\"font-family: sans-serif\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t            <li><a href=\"../admin/productList.jsp\">상품목록</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"../admin/adminMember.jsp\">회원목록</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"../admin/adminBoard.jsp\">게시판목록</a></li>\r\n");
      out.write("            \t</ul>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("<!--관리자 상품 등록-->\r\n");
      out.write("\r\n");
      out.write(" <section style=\"margin: 0 100px 0 100px ;\">\r\n");
      out.write("<h3 style=\"font-weight: bold; font-family: sans-serif;\">상품 개별보기</h3>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<form name=\"newProduct\" action=\"//작성\" class=\"form-horizontal\" method=\"post\" \r\n");
      out.write("\t\tenctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\r\n");
      out.write("<div>\r\n");
      out.write(" <table class=\"table\" style=\"border-top: 2px solid #333;\">\r\n");
      out.write("   <tr>\r\n");
      out.write("   \t<td width=\"70\" align=\"center\">카테고리</td>\r\n");
      out.write("   \t<td>\r\n");
      out.write("   \t    (select로 입력한 값 불러오기)\r\n");
      out.write("   \t</td>\r\n");
      out.write("  <tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("   \t<td width=\"70\" align=\"center\">상품 이름</td>\r\n");
      out.write("   \t<td>\r\n");
      out.write("   \t    망고\r\n");
      out.write("   \t</td>\r\n");
      out.write("  <tr>\r\n");
      out.write("   \t<td width=\"70\" align=\"center\"> 가격 </td>\r\n");
      out.write("   \t<td>\r\n");
      out.write("\t   \t19,000원\r\n");
      out.write("   \t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  \r\n");
      out.write("   <tr>\r\n");
      out.write("   \t<td width=\"70\" align=\"center\" > 상세 내용 </td>\r\n");
      out.write("   \t<td width=\"300\" align=\"left\">태국산 망고 입니다. (상품 설명)</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("      <td width=\"70\" align=\"center\" >상품 이미지</td>\r\n");
      out.write("      <td><img src=\"../assets/images/product/product2.PNG\" style=\"height: 200px;\"></td>\r\n");
      out.write("   <tr>\r\n");
      out.write("\t<td align=\"right\" colspan=\"2\"> \r\n");
      out.write("   \t\t    <input type=\"submit\" class=\"btn_update\" value=\"수정하기\" style=\"background-color: #378bb3 ;\">\r\n");
      out.write("   \t\t    \r\n");
      out.write("   \t\t    <input type=\"button\" class=\"btn_delete\" value=\"글삭제\" style=\"background-color: #378bb3 ;\">\r\n");
      out.write("           \r\n");
      out.write("            <input type=\"button\" class=\"btn_list\" value=\"목록\" style=\"background-color: #378bb3 ;\">\r\n");
      out.write("\r\n");
      out.write("   \t\t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write(" </table>\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("</section>\r\n");
      out.write("<!--푸터-->\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t<div id=\"footer\" class=\"fh5co-border-line\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-8 col-md-offset-2 text-center\">\r\n");
      out.write("\t\t\t\t\t\t<p>Copyright 2016 Free Html5 <a href=\"#\">Neos</a>. All Rights Reserved. <br>Made with <i class=\"icon-heart3 love\"></i> by <a href=\"http://freehtml5.co/\" target=\"_blank\">Freehtml5.co</a> / Demo Images: <a href=\"https://www.pexels.com/\" target=\"_blank\">Pexels</a> &amp; <a href=\"http://plmd.me/\" target=\"_blank\">PLMD</a> </p>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"fh5co-social-icons\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"><i class=\"icon-twitter-with-circle\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"><i class=\"icon-facebook-with-circle\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"><i class=\"icon-instagram-with-circle\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\r\n");
      out.write("\t<!-- jQuery -->\r\n");
      out.write("\t<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("\t<!-- jQuery Easing -->\r\n");
      out.write("\t<script src=\"js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("\t<!-- Bootstrap -->\r\n");
      out.write("\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<!-- Waypoints -->\r\n");
      out.write("\t<script src=\"js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("\t<!-- Owl carousel -->\r\n");
      out.write("\t<script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("\t<!-- Stellar -->\r\n");
      out.write("\t<script src=\"js/jquery.stellar.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Main JS (Do not remove) -->\r\n");
      out.write("\t<script src=\"js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
