/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2021-05-10 05:58:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.aa;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class oderList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<!--  Bootstrap -->\r\n");
      out.write("<link href =\"../assets/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href =\"../assets/css/custom.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../assets/css/mypage.css\" rel=\"stylesheet\">\r\n");
      out.write(" \r\n");
      out.write(" \t<!-- 주문내역 기간별 드롭다운 스크립트 -->\r\n");
      out.write("  \t\t\t<script>\r\n");
      out.write("  \t\t\t\t$('.search_data .btn_layer').on('click', function(e){\r\n");
      out.write("  \t\t\t\t\te.preventDefault();\r\n");
      out.write("  \t\t\t\t\t$(this).toggleClass('on');\r\n");
      out.write("  \t\t\t\t\t$('.search_data .layer_search').slideToggle(100);\r\n");
      out.write("  \t\t\t\t});\r\n");
      out.write("  \t\t\t</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  \t<div class=\"container\">\r\n");
      out.write("  \t\t<div id = \"content\">\r\n");
      out.write("  \t\t\t<div class=\"page_aticle\">\r\n");
      out.write("  \t\t\t\t<div id=\"snb\" class=\"snb_my\">\r\n");
      out.write("  \t\t\t\t\t<h2 class=\"tit_snb\">마이컬리</h2>\r\n");
      out.write("  \t\t\t\t\t<div class=\"inner_snb\">\r\n");
      out.write("  \t\t\t\t\t\t<ul class=\"list_menu\">\r\n");
      out.write("  \t\t\t\t\t\t\t<li class=\"on\">\r\n");
      out.write("  \t\t\t\t\t\t\t\t<a href=\"#\">주문 내역</a>\r\n");
      out.write("  \t\t\t\t\t\t\t</li>\r\n");
      out.write("  \t\t\t\t\t\t\t<li>\r\n");
      out.write("  \t\t\t\t\t\t\t\t<a href=\"#\">상품 후기</a>\r\n");
      out.write("  \t\t\t\t\t\t\t</li>\r\n");
      out.write("  \t\t\t\t\t\t\t<li>\r\n");
      out.write("  \t\t\t\t\t\t\t\t<a href=\"privacyUpdate.jsp\">개인 정보 수정</a>\r\n");
      out.write("  \t\t\t\t\t\t\t</li>\r\n");
      out.write("  \t\t\t\t\t\t</ul>\r\n");
      out.write("  \t\t\t\t\t</div> <!-- inner snb 끝 -->\r\n");
      out.write("  \t\t\t\t\t\t<a href=\"#\" class=\"link_inquire\">\r\n");
      out.write("  \t\t\t\t\t\t\t<span class=\"emph\">도움이 필요하신가요 ?<br></span>\r\n");
      out.write("  \t\t\t\t\t\t\t\"1:1 문의하기\"\r\n");
      out.write("  \t\t\t\t\t\t</a>\t\r\n");
      out.write("  \t\t\t\t</div> <!-- 사이드바 끝 -->\r\n");
      out.write("  \t\t\t\t\r\n");
      out.write("  \t\t\t\t\t<!-- 마이페이지 본문 시작 -->\r\n");
      out.write("  \t\t\t\t<div id=\"viewOrderList\" class=\"page_section section_orderlist\">\r\n");
      out.write("  \t\t\t\t\t<div class=\"head_aticle\">\r\n");
      out.write("  \t\t\t\t\t\t<h2 class=\"tit\">주문 내역\r\n");
      out.write("  \t\t\t\t\t\t<span class=\"tit_sub\">지난 1년간의 주문 내역 조회가 가능합니다.</span>\r\n");
      out.write("  \t\t\t\t\t\t</h2>\r\n");
      out.write("  \t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t\t\r\n");
      out.write("  \t\t\t\t\t<div class=\"search_data\">\r\n");
      out.write("  \t\t\t\t\t\t<h3 class=\"screen_out\">기간 선택</h3>\r\n");
      out.write("  \t\t\t\t\t\t<a href=\"#\" class=\"btn_layer\">\r\n");
      out.write("  \t\t\t\t\t\t\t전체기간\r\n");
      out.write("  \t\t\t\t\t\t</a>\r\n");
      out.write("  \t\t\t\t\t\t<ul class=\"layer_search\">\r\n");
      out.write("  \t\t\t\t\t\t\t<li><a href=\"#\" class=\"on\">전체기간</a></li>\r\n");
      out.write("  \t\t\t\t\t\t\t<li><a href=\"#\" data-year=\"2021\">2021년</a></li>\r\n");
      out.write("  \t\t\t\t\t\t\t<li><a href=\"#\" data-year=\"2020\">2020년</a></li>\r\n");
      out.write("  \t\t\t\t\t\t</ul>\r\n");
      out.write("  \t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t\t\r\n");
      out.write("  \t\t\t\t\t<!-- 주문 리스트 -->\r\n");
      out.write("  \t\t\t\t\t<ul class=\"list_order\">\r\n");
      out.write("  \t\t\t\t\t\t<li class=\"no_data\">\r\n");
      out.write("  \t\t\t\t\t\t주문내역이 없습니다.\r\n");
      out.write("  \t\t\t\t\t\t</li>\r\n");
      out.write("  \t\t\t\t\t</ul>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t\r\n");
      out.write("  \t\t\t</div> <!-- 마이페이지 전체적인 레이아웃 (사이드바, 본문 포함 -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div> <!-- content -->\r\n");
      out.write("    </div> <!-- container -->\r\n");
      out.write("   \r\n");
      out.write("    \t\t\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
