/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2021-05-10 06:57:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!--[if lt IE 7]>      <html class=\"no-js lt-ie9 lt-ie8 lt-ie7\"> <![endif]-->\r\n");
      out.write("<!--[if IE 7]>         <html class=\"no-js lt-ie9 lt-ie8\"> <![endif]-->\r\n");
      out.write("<!--[if IE 8]>         <html class=\"no-js lt-ie9\"> <![endif]-->\r\n");
      out.write("<!--[if gt IE 8]><!-->\r\n");
      out.write("<html class=\"no-js\">\r\n");
      out.write("<!--<![endif]-->\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\t<title>BIT KURLY</title>\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t<meta name=\"description\" content=\"Free HTML5 Template by FREEHTML5.CO\" />\r\n");
      out.write("\t<meta name=\"keywords\" content=\"free html5, free template, free bootstrap, html5, css3, mobile first, responsive\" />\r\n");
      out.write("\t<meta name=\"author\" content=\"FREEHTML5.CO\" />\r\n");
      out.write("\r\n");
      out.write("\t<!-- \r\n");
      out.write("\t//////////////////////////////////////////////////////\r\n");
      out.write("\r\n");
      out.write("\tFREE HTML5 TEMPLATE \r\n");
      out.write("\tDESIGNED & DEVELOPED by FREEHTML5.CO\r\n");
      out.write("\t\t\r\n");
      out.write("\tWebsite: \t\thttp://freehtml5.co/\r\n");
      out.write("\tEmail: \t\t\tinfo@freehtml5.co\r\n");
      out.write("\tTwitter: \t\thttp://twitter.com/fh5co\r\n");
      out.write("\tFacebook: \t\thttps://www.facebook.com/fh5co\r\n");
      out.write("\r\n");
      out.write("\t//////////////////////////////////////////////////////\r\n");
      out.write("\t -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Facebook and Twitter integration -->\r\n");
      out.write("\t<meta property=\"og:title\" content=\"\" />\r\n");
      out.write("\t<meta property=\"og:image\" content=\"\" />\r\n");
      out.write("\t<meta property=\"og:url\" content=\"\" />\r\n");
      out.write("\t<meta property=\"og:site_name\" content=\"\" />\r\n");
      out.write("\t<meta property=\"og:description\" content=\"\" />\r\n");
      out.write("\t<meta name=\"twitter:title\" content=\"\" />\r\n");
      out.write("\t<meta name=\"twitter:image\" content=\"\" />\r\n");
      out.write("\t<meta name=\"twitter:url\" content=\"\" />\r\n");
      out.write("\t<meta name=\"twitter:card\" content=\"\" />\r\n");
      out.write("\r\n");
      out.write("\t<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->\r\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet' type='text/css'> -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Animate.css -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/animate.css\">\r\n");
      out.write("\t<!-- Icomoon Icon Fonts-->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/icomoon.css\">\r\n");
      out.write("\t<!-- Bootstrap  -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/bootstrap.css\">\r\n");
      out.write("\t<!-- Owl Carousel -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/owl.carousel.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/owl.theme.default.min.css\">\r\n");
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/style.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/index.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Modernizr JS -->\r\n");
      out.write("\t<script src=\"assets/js/modernizr-2.6.2.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/index.js\"></script>\r\n");
      out.write("\t<!-- FOR IE9 below -->\r\n");
      out.write("\t<!--[if lt IE 9]>\r\n");
      out.write("\t<script src=\"js/respond.min.js\"></script>\r\n");
      out.write("\t<![endif]-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"header\">\r\n");
      out.write("\t\t<div id=\"userMenu\">\r\n");
      out.write("\t\t\t<!-- <div></div> 샛별배송 없애는 대신 div태그 가능-->\r\n");
      out.write("\t\t\t<div class=\"sub_tit\" style=\"font-size: 13px;\">샛별배송</div>\r\n");
      out.write("\t\t\t<ul class=\"list_menu\">\r\n");
      out.write("\t\t\t\t<li class=\"menu none_sub menu_join\"><a href=\"../join/signUp.html\" class=\"link_menu\">회원가입</a></li> \r\n");
      out.write("\t\t\t\t<span class=\"bar\"></span>\r\n");
      out.write("\t\t\t\t<li class=\"menu none_sub menu_login\"><a href=\"../join/logIn.html\" class=\"link_menu\">로그인</a></li>\r\n");
      out.write("\t\t\t\t<span class=\"bar\"></span>\r\n");
      out.write("\t\t\t\t<li class=\"menu lst dropdown\"><a href=\"#\" class=\"link_menu\"><button class=\"dropbtn\">고객센터 ▼</button></a>\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown-content\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">공지사항</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">자주하는 질문</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">1:1문의</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">게시판</a>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<header style=\"padding-bottom: 3px\">\r\n");
      out.write("\t\t<div class=\"container text-center\">\r\n");
      out.write("\t\t\t<div class=\"fh5co-navbar-brand\">\r\n");
      out.write("\t\t\t\t<a class=\"fh5co-logo\" href=\"index.html\" style=\"font-size: 15px\">bit kurly</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<nav id=\"fh5co-main-nav\" role=\"navigation\" style=\"font-family: sans-serif\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"index.html\" class=\"active\">신상품</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"work.html\">베스트</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"services.html\">알뜰쇼핑</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"about.html\">금주혜택</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t</header>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"owl-carousel owl-carousel1 owl-carousel-fullwidth fh5co-light-arrow animate-box\"\r\n");
      out.write("\t\tdata-animate-effect=\"fadeIn\">\r\n");
      out.write("\t\t<div class=\"item\"><a href=\"../assets/images/join/main1-big.png\" class=\"image-popup\"><img src=\"../assets/images/join/main1.png\"\r\n");
      out.write("\t\t\t\t\talt=\"image\"></a></div>\r\n");
      out.write("\t\t<div class=\"item\"><a href=\"../assets/images/join/main2-big.png\" class=\"image-popup\"><img src=\"../assets/images/join/main2.png\"\r\n");
      out.write("\t\t\t\t\talt=\"image\"></a></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!--1.이상품 어때요? -->\r\n");
      out.write("\t<!--상세정보와 연동-->\r\n");
      out.write("\t<div id=\"fh5co-featured-work-section\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<div class=\"heading-section text-center\">\r\n");
      out.write("\t\t\t\t<h2 style=\"font-family: sans-serif; font-size: 30px\">이 상품 어때요?</h2>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"owl-carousel owl-carousel2 loop\" >\r\n");
      out.write("\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t<img src=\"../assets/images/join/item1.png\" alt=\"image\" >\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"pop-up-overlay text-center\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>딸기 바나나 믹스 1kg(냉동)</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"price\">6900원</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t<img src=\"../assets/images/join/item2.png\" alt=\"image\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"pop-up-overlay pop-up-overlay-color-2 text-center\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>[혼신마켓]명란 마요네즈</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"price\">6500원</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t<img src=\"../assets/images/join/item3.png\" alt=\"image\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"pop-up-overlay pop-up-overlay-color-3 text-center\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>[KF365]아보카도 1개</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"price\">2200원</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t<img src=\"../assets/images/join/item4.png\" alt=\"image\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"pop-up-overlay pop-up-overlay-color-4 text-center\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>[쌜모네키친]오로라 생연어(냉장)</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"price\">14000원</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!--두번째 (HOT) -->\r\n");
      out.write("\t<div id=\"fh5co-featured-work-section\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<div class=\"heading-section text-center\">\r\n");
      out.write("\t\t\t\t<h2 style=\"font-family: sans-serif; font-size: 30px\">지금 가장 핫한 상품 > </h2>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"owl-carousel owl-carousel2\">\r\n");
      out.write("\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t<!-- <a href=\"#\" class=\"image-popup\"> -->\r\n");
      out.write("\t\t\t\t\t<img src=\"../assets/images/join/hot1.png\" alt=\"image\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"pop-up-overlay text-center\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>[남향푸드또띠아]간편 간식 브리또 10종</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"price\">2900원</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t<img src=\"../assets/images/join/hot2.png\" alt=\"image\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"pop-up-overlay pop-up-overlay-color-2 text-center\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>[KF365]DOLE 실속 바나나 1.1KG</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"price\">2900원</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t<!-- <a href=\"#\" class=\"image-popup\"> -->\r\n");
      out.write("\t\t\t\t\t<img src=\"../assets/images/join/hot3.png\" alt=\"image\">\r\n");
      out.write("\t\t\t\t\t<!-- </a> -->\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"pop-up-overlay pop-up-overlay-color-3 text-center\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>[Kurly's]국산콩 두부 300g</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"price\">1900원</span>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t<!-- <a href=\"#\" class=\"image-popup\"> -->\r\n");
      out.write("\t\t\t\t\t<img src=\"../assets/images/join/hot4.png\" alt=\"image\">\r\n");
      out.write("\t\t\t\t\t<!-- </a> -->\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"pop-up-overlay pop-up-overlay-color-4 text-center\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>[연세우유x마켓컬리]전용목장우유</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"price\">1850원</span>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t<img src=\"../assets/images/join/hot5.png\" alt=\"image\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"pop-up-overlay text-center\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>[청정원]라이틀리 곤약 볶음밥4종</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"price\">2300원</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- <div class=\"item\">\r\n");
      out.write("\t\t\t\t\t<img src=\"images/portfolio_pic6.jpg\" alt=\"image\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"pop-up-overlay pop-up-overlay-color-2 text-center\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>Shoes</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<span>Brand</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t<img src=\"images/portfolio_pic7.jpg\" alt=\"image\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"pop-up-overlay text-center\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>Magazine</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<span>Web</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t<img src=\"images/portfolio_pic8.jpg\" alt=\"image\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"pop-up-overlay pop-up-overlay-color-3 text-center\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>VCard</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<span>Card</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t<img src=\"images/portfolio_pic9.jpg\" alt=\"image\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"pop-up-overlay pop-up-overlay-color-4 text-center\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>Paper</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<span>Illustration</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"fh5co-featured-work-section\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<div class=\"heading-section text-center\">\r\n");
      out.write("\t\t\t\t<h2 style=\"font-family: sans-serif; font-size: 30px\">알뜰쇼핑</h2>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"owl-carousel owl-carousel2 loop\" >\r\n");
      out.write("\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t<img src=\"../assets/images/join/sale1.png\" alt=\"image\" >\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"pop-up-overlay text-center\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>[안국건강]<br> 안심 멀티비타민미네랄</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"price\">55000원</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t<img src=\"../assets/images/join/sale2.png\" alt=\"image\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"pop-up-overlay pop-up-overlay-color-2 text-center\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>[한미양행]아르간오일 30캡슐</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"price\">19000원</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t<img src=\"../assets/images/join/sale3.png\" alt=\"image\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"pop-up-overlay pop-up-overlay-color-3 text-center\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>[한미양행]한미 숙취환 14포</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"price\">30000원</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t<img src=\"../assets/images/join/sale4.png\" alt=\"image\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"pop-up-overlay pop-up-overlay-color-4 text-center\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>[한미양행]크릴오일캡슐(30캡슐)</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"price\">27000원</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- end fh5co-featured-work-section -->\r\n");
      out.write("\t<!-- <div id=\"fh5co-blog-section\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"heading-section text-center\">\r\n");
      out.write("\t\t\t\t<h2>Recent Blog</h2>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 blog-section\">\r\n");
      out.write("\t\t\t\t\t<span>03 <small>July 2016</small></span>\r\n");
      out.write("\t\t\t\t\t<h3><a href=\"#\">Mourntains countries Vokalia</a></h3>\r\n");
      out.write("\t\t\t\t\t<p>Far far away, behind the word mountains, far from the countries Vokalia, there live the blind\r\n");
      out.write("\t\t\t\t\t\ttexts.</p>\r\n");
      out.write("\t\t\t\t\t<a class=\"btn btn-primary\" href=\"#\">Read More</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 blog-section\">\r\n");
      out.write("\t\t\t\t\t<span>02 <small>July 2016</small></span>\r\n");
      out.write("\t\t\t\t\t<h3><a href=\"#\">Mourntains countries Vokalia</a></h3>\r\n");
      out.write("\t\t\t\t\t<p>Far far away, behind the word mountains, far from the countries Vokalia, there live the blind\r\n");
      out.write("\t\t\t\t\t\ttexts.</p>\r\n");
      out.write("\t\t\t\t\t<a class=\"btn btn-primary\" href=\"#\">Read More</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 blog-section\">\r\n");
      out.write("\t\t\t\t\t<span>01 <small>July 2016</small></span>\r\n");
      out.write("\t\t\t\t\t<h3><a href=\"#\">Mourntains countries Vokalia</a></h3>\r\n");
      out.write("\t\t\t\t\t<p>Far far away, behind the word mountains, far from the countries Vokalia, there live the blind\r\n");
      out.write("\t\t\t\t\t\ttexts.</p>\r\n");
      out.write("\t\t\t\t\t<a class=\"btn btn-primary\" href=\"#\">Read More</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div> -->\r\n");
      out.write("\t<!-- end: fh5co-blog-section -->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"heading-section text-center\">\r\n");
      out.write("\t\t<h2 style=\"font-family: sans-serif; font-size: 30px\">금주혜택 모아보기</h2>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"benefit_img\">\r\n");
      out.write("\t\t<a href=\"#\"><img src=\"../assets/images/join/benefit.png\" alt=\"image\" ></a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- <div class=\"fh5co-parallax\" style=\"background-image: url(images/hero-2.jpg);\" data-stellar-background-ratio=\"0.5\">\r\n");
      out.write("\t\t<div class=\"overlay\"></div>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\tclass=\"col-md-8 col-md-offset-2 col-sm-12 col-sm-offset-0 col-xs-12 col-xs-offset-0 text-center fh5co-table\">\r\n");
      out.write("\t\t\t\t\t<div class=\"fh5co-intro fh5co-table-cell\">\r\n");
      out.write("\t\t\t\t\t\t<h1 class=\"text-center\">금주혜택</h1>\r\n");
      out.write("\t\t\t\t\t\t<p>Made with love by the fine folks at <a href=\"\">FreeHTML5.co</a></p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div> -->\r\n");
      out.write("\t<!-- end: fh5co-parallax -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t<div id=\"footer\" class=\"fh5co-border-line\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-8 col-md-offset-2 text-center\">\r\n");
      out.write("\t\t\t\t\t\t<p>Copyright 2016 Free Html5 <a href=\"#\">Neos</a>. All Rights Reserved. <br>Made with <i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"icon-heart3 love\"></i> by <a href=\"http://freehtml5.co/\"\r\n");
      out.write("\t\t\t\t\t\t\t\ttarget=\"_blank\">Freehtml5.co</a> / Demo Images: <a href=\"https://www.pexels.com/\"\r\n");
      out.write("\t\t\t\t\t\t\t\ttarget=\"_blank\">Pexels</a> &amp; <a href=\"http://plmd.me/\" target=\"_blank\">PLMD</a> </p>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"fh5co-social-icons\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"><i class=\"icon-twitter-with-circle\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"><i class=\"icon-facebook-with-circle\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"><i class=\"icon-instagram-with-circle\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\r\n");
      out.write("\t<!-- jQuery -->\r\n");
      out.write("\t<script src=\"assets/js/jquery.min.js\"></script>\r\n");
      out.write("\t<!-- jQuery Easing -->\r\n");
      out.write("\t<script src=\"assets/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("\t<!-- Bootstrap -->\r\n");
      out.write("\t<script src=\"assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<!-- Waypoints -->\r\n");
      out.write("\t<script src=\"assets/js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("\t<!-- Owl carousel -->\r\n");
      out.write("\t<script src=\"assets/js/owl.carousel.min.js\"></script>\r\n");
      out.write("\t<!-- Stellar -->\r\n");
      out.write("\t<script src=\"assets/js/jquery.stellar.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Main JS (Do not remove) -->\r\n");
      out.write("\t<script src=\"assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
